apiVersion: v1
kind: Service
metadata:
  name: kube-sample
  labels:
    app: kube-sample
    app-version: $APP_VERSION
spec:
  selector:
    app: kube-sample
    app-version: $APP_VERSION
  ports:
  - port: 8080
